name: Docker Image CI

on:
  push:
    branches: [ sujin ]
  pull_request:
    branches: [ sujin ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Deploy to EB # (2)
          uses: einaregilsson/beanstalk-deploy@v14
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            application_name: freelec-springboot2-webervice
            environment_name: freelec-springboot2-webervice
            region: us-east-2
            deployment_package: deploy/deploy.zip